#!/opt/rh/python27/root/usr/bin/python

#    This software is Copyright by the Board of Trustees of Michigan State
#    University (c) Copyright 2014. 
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#     Author:
#      Jeromy Tompkins
#	     NSCL
#	     Michigan State University
#	     East Lansing, MI 48824-1321

from sys import argv
from subprocess import call
from os import path
from shutil import move

completedir = path.join('/user','e09084','stagearea','complete')

if len(argv) < 3:
	print """\
Usage: ./gofilter proto path 

    uri - either file:// or tcp://

    path - either run number if file:// proto or hostname/ringname

EXAMPLES
    ./gofilter file:// 100 

    ./gofilter tcp:// hostname/ringname
"""
	exit(1)

def getRunPath(num):
	completedir = '../../evtfiles/run{}'.format(int(num))
	tail = 'run-{:04d}-00.evt'.format(int(num))
	runname = path.join(completedir,tail)
	return runname

def getResultPath(num):
	tail = '../../rootfiles/run-{:04d}-00-analyzed.root'.format(int(num))
	runname = tail
	return runname

if argv[1] == 'file://':
	runpath = getRunPath(argv[2])
#cmd = './UserFilter --source={}{} --sink=file:///dev/null --oneshot'.format(argv[1],runpath)
	cmd = './UserFilter --source={}{} --sink=file:///dev/null '.format(argv[1],runpath)
else :
#cmd = './UserFilter --source={}{} --sink=file:///dev/null --oneshot'.format(argv[1],argv[2])
	cmd = './UserFilter --source={}{} --sink=file:///dev/null '.format(argv[1],argv[2])

print cmd
call(cmd,shell=True)

move('analyzer.root', getResultPath(argv[2]))
